### ISSUE TITLE
Usmap has invalid version

### ISSUE THREAD

**Issue by Ljzd-PRO** [JsonAsAsset/JsonAsAsset#46]
```
[CORE] Initializing globals, and provider..
[Provider] Found config folder: C:\Users\mcdha\Documents\Unreal Projects\BC_PD\Config
[UserSettings] Mappings: C:/Users/mcdha/Downloads/FModel/Bodycam.usmap
[UserSettings] Archive Directory: C:/Program Files/Bodycam
[UserSettings] Unreal Versioning: GAME_UE5_2
Unhandled exception. CUE4Parse.UE4.Exceptions.ParserException: Usmap has invalid version (3)
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(FArchive archive) in D:\Portnite\5.3\FortniteGame\Plugins\JsonAsAsset\JsonAsAsset\ExternalSource\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapParser.cs:line 35
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(Stream data, String name) in D:\Portnite\5.3\FortniteGame\Plugins\JsonAsAsset\JsonAsAsset\ExternalSource\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapParser.cs:line 24
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(String path, String name) in D:\Portnite\5.3\FortniteGame\Plugins\JsonAsAsset\JsonAsAsset\ExternalSource\CUE4Parse\CUE4Parse\MappingsProvider\Usmap\UsmapParser.cs:line 23
   at CUE4Parse.MappingsProvider.UsmapTypeMappingsProvider.Load(String path) in D:\Portnite\5.3\FortniteGame\Plugins\JsonAsAsset\JsonAsAsset\ExternalSource\CUE4Parse\CUE4Parse\MappingsProvider\UsmapTypeMappingsProvider.cs:line 11
   at CUE4Parse.MappingsProvider.FileUsmapTypeMappingsProvider..ctor(String path) in D:\Portnite\5.3\FortniteGame\Plugins\JsonAsAsset\JsonAsAsset\ExternalSource\CUE4Parse\CUE4Parse\MappingsProvider\FileUsmapTypeMappingsProvider.cs:line 14
   at Globals.Initialize() in D:\Portnite\5.3\FortniteGame\Plugins\JsonAsAsset\JsonAsAsset\ExternalSource\LocalFetch\Controllers\JsonAsAssetController.cs:line 151
   at Program.<Main>$(String[] args) in D:\Portnite\5.3\FortniteGame\Plugins\JsonAsAsset\JsonAsAsset\ExternalSource\LocalFetch\Program.cs:line 7
   at Program.<Main>(String[] args)
```
But FModel can successfully load the game files using the same Usmap with same GAME_UE5_2 version setting.

**Comment by Ljzd-PRO** [comment]
![image](https://github.com/user-attachments/assets/3515c87a-c689-4c57-902a-bc6a71d7c8e6)
![image](https://github.com/user-attachments/assets/07f63f8f-80ab-44cb-9c6f-2cc6c4294377)
![image](https://github.com/user-attachments/assets/13d117fb-3a73-49da-b5a9-b2afa22abc06)

**Comment by Tectors** [comment]
Was this resolved?
